version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpu-leaderboard
    restart: unless-stopped
    ports:
      - "3000:3000"  # Main server
      - "6969:6969"  # Admin server
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - ADMIN_PORT=${ADMIN_PORT:-6969}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge